[automap]
target1="anex86.exe"
target2="np21.exe"
target3="np21nt.exe"
target4="np2sx.exe"
target5="np2sxnt.exe"
target6="np2nt.exe"
target7="np2.exe"
target8="np2w.exe"
target9="np2x64w.exe"
target10="np21w.exe"
target11="np21x64w.exe"
target12="Next.EXE"
target13="WIZ7.EXE"
target14=
target15=
target16=
enable=true
show_tooltips=true
hide_in_dark_zones=true
width=512
height=512
position_x=-1
position_y=-1
wiz7_sns_mode=false
